import React from 'react'

const HowItWorks = () => {
  return (
    <div className='how-it-section'>
        <div className="container">
            <div className="row">
                <div className="col-md-7">
                    <div className="how-it-left">
                        <div className="how-it-img">
                            <img src="./images/img/how-work-img.png" alt="img" />
                        </div>
                    </div>
                </div>
                <div className="col-md-5">
                    <div className="how-it-right">
                        <div className="how-it-text">
                            <h2 className='section-title'>
                                How It Works
                            </h2>
                            <div className="how-it-content">
                                <ul>
                                    <li>
                                        <div className="icon">
                                            <img src="./images/icons/energy.svg" alt="icon" />
                                        </div>
                                        <div className="detail">
                                            <h3>Renewable Energy Projects</h3>
                                            <p>Solar farms, wind turbines, and hydroelectric plants generate clean energy. The revenue generated from these sources forms the basis of Renewtrade's income-sharing model.</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div className="icon">
                                            <img src="./images/icons/token.svg" alt="icon" />
                                        </div>
                                        <div className="detail">
                                            <h3>The Renewtrade Token</h3>
                                            <p>Tokenholders receive a share of the profits generated by these energy projects. Up to 50% of the net profits are distributed based on the tiered structure of investments.</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div className="icon">
                                            <img src="./images/icons/trust.svg" alt="icon" />
                                        </div>
                                        <div className="detail">
                                            <h3>Transparency & Trust</h3>
                                            <p>Built on blockchain, all transactions are publicly recorded and verified. Independent audits are conducted to ensure accurate revenue distributions.</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  )
}

export default HowItWorks